export enum PROMOTION_PRODUCT_TYPE {
    BILLBOARD = 'BILLBOARD',
    LED = 'LED',
}

export enum AREA {
    INDUSTRIAL_AREA = 'INDUSTRIAL_AREA',
    SHOPPING_MALL = 'SHOPPING_MALL',
    SCHOOL = 'SCHOOL',
    AIRPORT = 'AIRPORT',
    INTERSECTION = 'INTERSECTION',
    ROUNDABOUT = 'ROUNDABOUT',
    HIGHWAY = 'HIGHWAY',
    ROUTE = 'ROUTE',
    OTHERS = 'OTHERS',
}
