export enum PERMISSIONS {
    CREATE_PROMOTION_PRODUCT = 'CREATE_PROMOTION_PRODUCT',
    FIND_PROMOTION_PRODUCT = 'FIND_PROMOTION_PRODUCT',
    FIND_ALL_PROMOTION_PRODUCT = 'FIND_ALL_PROMOTION_PRODUCT',
    UPDATE_PROMOTION_PRODUCT = 'UPDATE_PROMOTION_PRODUCT',
    DELETE_PROMOTION_PRODUCT = 'DELETE_PROMOTION_PRODUCT',

    CREATE_USER = 'CREATE_USER',
    FIND_USER = 'FIND_USER',
    FIND_ALL_USER = 'FIND_ALL_USER',
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',

    CREATE_ROLE = 'CREATE_ROLE',
    FIND_ROLE = 'FIND_ROLE',
    FIND_ALL_ROLE = 'FIND_ALL_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',

    CREATE_WISHLIST = 'CREATE_WISHLIST',
    FIND_WISHLIST = 'FIND_WISHLIST',
    FIND_ALL_WISHLIST = 'FIND_ALL_WISHLIST',
    UPDATE_WISHLIST = 'UPDATE_WISHLIST',
    DELETE_WISHLIST = 'DELETE_WISHLIST',

    CREATE_CONTACT = 'CREATE_CONTACT',
    FIND_CONTACT = 'FIND_CONTACT',
    FIND_ALL_CONTACT = 'FIND_ALL_CONTACT',
    UPDATE_CONTACT = 'UPDATE_CONTACT',
    DELETE_CONTACT = 'DELETE_CONTACT',

    CREATE_COUNTRY = 'CREATE_COUNTRY',
    FIND_COUNTRY = 'FIND_COUNTRY',
    FIND_ALL_COUNTRY = 'FIND_ALL_COUNTRY',
    UPDATE_COUNTRY = 'UPDATE_COUNTRY',
    DELETE_COUNTRY = 'DELETE_COUNTRY',

    CREATE_CITY = 'CREATE_CITY',
    FIND_CITY = 'FIND_CITY',
    FIND_ALL_CITY = 'FIND_ALL_CITY',
    UPDATE_CITY = 'UPDATE_CITY',
    DELETE_CITY = 'DELETE_CITY',

    CREATE_DISTRICT = 'CREATE_DISTRICT',
    FIND_DISTRICT = 'FIND_DISTRICT',
    FIND_ALL_DISTRICT = 'FIND_ALL_DISTRICT',
    UPDATE_DISTRICT = 'UPDATE_DISTRICT',
    DELETE_DISTRICT = 'DELETE_DISTRICT',

    CREATE_WARD = 'CREATE_WARD',
    FIND_WARD = 'FIND_WARD',
    FIND_ALL_WARD = 'FIND_ALL_WARD',
    UPDATE_WARD = 'UPDATE_WARD',
    DELETE_WARD = 'DELETE_WARD',

    CREATE_ENVIRONMENT = 'CREATE_ENVIRONMENT',
    FIND_ENVIRONMENT = 'FIND_ENVIRONMENT',
    FIND_ALL_ENVIRONMENT = 'FIND_ALL_ENVIRONMENT',
    UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT',
    DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT',

    FIND_PDF = 'FIND_PDF',
    FIND_PPT = 'FIND_PPT',
    FIND_EXCEL = 'FIND_EXCEL',

    ACCESS_DASHBOARD = 'ACCESS_DASHBOARD',
}
