version: "3.8"
services:
  g2b-api:
    image: fxanhkhoa/g2b-api:latest
    container_name: g2b-api
    restart: always
    ports:
        - 3007:3000
    env_file:
        - .env
    volumes:
        - type: volume
          source: g2b-api-data
          target: /upload

volumes:
  g2b-api-data: